function f = getLiveEditorFigurePool
    r = groot;
    f = findobj(r.NodeChildren, ...
        "type", "figure", ...
        "Tag", "EmbeddedFigure_Internal", ...
        "editorID", []);
end

% Copyright 2025-2026 Steven L. Eddins