function grp = pixelGridGroup(ax,xv,yv)
    grp = hggroup(...
        Parent = ax,...
        Tag = "imview_pixelgrid",...
        Visible = false);
    % bottom_line_color = lab2rgb([40 0 0]);
    bottom_line_color = 0.3695 * [1 1 1];
    % top_line_color = lab2rgb([70 0 0]);
    top_line_color = 0.6708 * [1 1 1];

    bottom_line_width = 0.5;
    top_line_width = 0.5;

    % When creating the lines, use AlignVertexCenters to avoid antialias
    % effects that would cause some lines in the grid to appear brighter than
    % others.
    line(                              ...
        Parent = grp,                  ...
        XData = xv,                    ...
        YData = yv,                    ...
        LineWidth = bottom_line_width, ...
        Color = bottom_line_color,     ...
        LineStyle = "-",               ...
        AlignVertexCenters = "on")

    line(...
        Parent = grp,               ...
        XData = xv,                 ...
        YData = yv,                 ...
        LineWidth = top_line_width, ...
        Color = top_line_color,     ...
        LineStyle = "--",           ...
        AlignVertexCenters = "on")
end

% Copyright 2025-2026 Steven L. Eddins